[[redirects]]
  from = "/api/*"
  to = "http://184.168.125.61/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "http://184.168.125.61/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
