[[redirects]]
  from = "/apk"
  to = "https://github.com/harryongit/k36b/releases/latest/download/milan36bazaar.apk"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "http://203.161.57.212/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "http://203.161.57.212/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

